# -*- coding: utf-8 -*-
"""Despliegue Modelo proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YewMxZH46Ty8N5V262G2Ezq22Lz-mC14

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

import streamlit as st
import pandas as pd
import pickle

# 1. Carga del entorno (Caché para optimizar memoria en producción)
@st.cache_resource
def cargar_entorno():
    filename = 'modelo-ensamble-reg.pkl'
    modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
    return modelo, min_max_scaler, variables

# Instanciación de los objetos exportados
modelo, min_max_scaler, variables = cargar_entorno()

# 2. Diseño de la Interfaz
st.markdown("""
<style>
    .stApp { background-color: #FCFBF9; }
    h1 {
        color: #2C3E50;
        font-family: 'Didot', 'Times New Roman', serif;
        text-align: center;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 15px;
        margin-bottom: 30px;
    }
    .stSelectbox label, .stSlider label { font-weight: 600; color: #34495E; font-size: 1.05rem; }
    div[data-baseweb="select"] > div { border-radius: 8px; border-color: #EAECEE; }
    div.stDataFrame { border: 1px solid #D4AF37; border-radius: 10px; }
</style>
""", unsafe_allow_html=True)

st.title('👗 Proyección de Ventas: Colección de Moda')

# 3. Captura de Datos de Usuario
Antiguedad_meses = st.slider('Antigüedad del Asesor (Meses)', min_value=1, max_value=120, value=12, step=1)
Categoria_prenda = st.selectbox('Categoría de Prenda', ["'Alta Costura'","'Casual'", "'Gala'","'Deportiva'","'Accesorios'","'Calzado'","'Básicos'","'Temporada'"])
Tipo_tienda = st.selectbox('Tipo de Tienda', ["'Boutique Principal'", "'Centro Comercial'","Outlet","Pop-up"])
Genero_objetivo = st.selectbox('Género Objetivo', ['Mujer', 'Hombre', 'Unisex'])
Campana_lanzamiento = st.selectbox('Campaña Activa', ['True', 'False'])

datos = [[Antiguedad_meses, Categoria_prenda, Tipo_tienda, Genero_objetivo, Campana_lanzamiento]]
data = pd.DataFrame(datos, columns=['Antiguedad_meses', 'Categoria_prenda', 'Tipo_tienda', 'Genero_objetivo', 'Campana_lanzamiento'])

# 4. Pipeline de Transformación (Orden estricto según notebook)
data_preparada = data.copy()

# A. Dummificación inicial
data_preparada = pd.get_dummies(data_preparada, columns=['Categoria_prenda', 'Tipo_tienda','Genero_objetivo', 'Campana_lanzamiento'], drop_first=False, dtype=int)

# B. Alineación matricial (Garantiza el mismo 'shape' que en entrenamiento)
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

# C. Normalización (Se aplica sobre la matriz ya dummificada y alineada)
# Retorna un numpy array.
data_escalada = min_max_scaler.transform(data_preparada)

# 5. Inferencia
# El modelo recibe el array escalado con las proporciones correctas.
Y_pred = modelo.predict(data_escalada)

# Asignación del resultado redondeado para presentación
data['Proyeccion_Venta_Mensual'] = Y_pred.round(2)

# 6. Despliegue
st.subheader("Resultado de la Proyección")
st.dataframe(data)

st.success("✅ Predicción generada aplicando las transformaciones en el orden validado.")