# -*- coding: utf-8 -*-
"""Despliegue Modelo proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YewMxZH46Ty8N5V262G2Ezq22Lz-mC14

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

import numpy as np
import pandas as pd
import streamlit as st
import pickle

# 1. Carga del modelo (fuera de funciones para aprovechar caché si se mejora después)
filename = 'modelo-ensamble-reg.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

st.title('Predicción de ventas por asesor')

# --- Variables numéricas ---
edad_asesor = st.slider('Edad del asesor', min_value=14.0, max_value=57.0, value=29.0, step=1.0)
total_dias_absentismo = st.slider('Total días absentismo', min_value=0.0, max_value=31.0, value=0.0, step=1.0)
cantidad_cajas = st.slider('Cantidad de cajas', min_value=1.0, max_value=4.0, value=2.0, step=1.0)
metros_cuadrados_tienda = st.number_input('Metros cuadrados de la tienda', min_value=50.0, max_value=329.0, value=150.0)

# Ventas históricas
venta_t_1 = st.number_input('Venta mes t-1', min_value=0.0, value=0.0, step=100000.0)
venta_t_2 = st.number_input('Venta mes t-2', min_value=0.0, value=0.0, step=100000.0)
venta_t_3 = st.number_input('Venta mes t-3', min_value=0.0, value=0.0, step=100000.0)

# --- Variables categóricas ---
genero_asesor = st.selectbox('Género del asesor', ['F', 'M'])
tipo_vinculacion = st.selectbox('Tipo de vinculación', ['INDEF', 'OBRA'])
nacionalidad_asesor = st.selectbox('Nacionalidad del asesor', ['COLOMBIA', 'EXTRANJERO', 'VENEZUELA'])
tipo_ubicacion_tienda = st.selectbox('Tipo ubicación tienda', ['CENTRO COMERCIAL', 'EXTERIOR'])
marca = st.selectbox('Marca', ['MARCA_A', 'MARCA_B', 'MARCA_C', 'MARCA_D'])
zona_comercial = st.selectbox('Zona comercial', ['MEDELLIN', 'BOGOTA', 'CALI', 'CARTAGENA', 'BARRANQUILLA', 'OTRA_ZONA'])
mes_venta = st.selectbox('Mes de venta', ['ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE'])

# 2. Control de ejecución mediante botón
if st.button('Generar Predicción'):
    
    # Dataframe de entrada
    datos = [[genero_asesor, edad_asesor, tipo_vinculacion, nacionalidad_asesor, total_dias_absentismo,
              tipo_ubicacion_tienda, marca, zona_comercial, cantidad_cajas, metros_cuadrados_tienda,
              mes_venta, venta_t_1, venta_t_2, venta_t_3]]
    
    columnas_entrada = ['genero_asesor', 'edad_asesor', 'tipo_vinculacion', 'nacionalidad_asesor',
                        'total_dias_absentismo', 'tipo_ubicacion_tienda', 'marca', 'zona_comercial',
                        'cantidad_cajas', 'metros_cuadrados_tienda', 'mes_venta', 'venta_t_1',
                        'venta_t_2', 'venta_t_3']
    
    data = pd.DataFrame(datos, columns=columnas_entrada)

    # Preparación de datos
    data_preparada = pd.get_dummies(data, columns=['genero_asesor', 'tipo_vinculacion', 'nacionalidad_asesor',
                                                   'tipo_ubicacion_tienda', 'marca', 'zona_comercial', 'mes_venta'],
                                    drop_first=False, dtype=int)

    # Alinear columnas con el entrenamiento
    data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

    # Escalar variables numéricas
    data_preparada['valor_venta_asesor_mes_t'] = 0.0
    col_numericas = ['edad_asesor', 'total_dias_absentismo', 'cantidad_cajas', 'metros_cuadrados_tienda',
                     'venta_t_1', 'venta_t_2', 'venta_t_3', 'valor_venta_asesor_mes_t']
    
    data_preparada[col_numericas] = min_max_scaler.transform(data_preparada[col_numericas])

    # 📌 ELIMINAR LA VARIABLE OBJETIVO ANTES DE PREDECIR (Corrección del Error 1)
    data_preparada = data_preparada.drop(columns=['valor_venta_asesor_mes_t'])

    # Predicción
    Y_pred_normalizado = modelo.predict(data_preparada)

    # Des-normalizar
    temp_array = np.zeros((len(Y_pred_normalizado), len(col_numericas)))
    indice_target = col_numericas.index('valor_venta_asesor_mes_t')
    temp_array[:, indice_target] = Y_pred_normalizado
    temp_array_inverso = min_max_scaler.inverse_transform(temp_array)
    Y_pred_pesos = temp_array_inverso[:, indice_target]

    # 📌 MOSTRAR RESULTADOS EN LA INTERFAZ (Corrección del Error 2)
    st.success(f"Predicción generada con éxito")
    st.metric(label="Venta Estimada (Pesos COP)", value=f"${Y_pred_pesos[0]:,.2f}")
    
    # Mostrar el dataframe enriquecido
    data['Prediccion'] = Y_pred_pesos
    st.dataframe(data)

st.warning("Se selecciona el MAE y se descarta el MAPE porque la variable objetivo contiene meses donde las ventas fueron cero, este modelo tiene un error de 3.58%")
